apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- namespace.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml
images:
- name: 134978288309.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 24f8816fd8ce73f3ef6ecc2a3a1b219cd60d94d6
