apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- namespace.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml
images:
- name: 134978288309.dkr.ecr.us-east-2.amazonaws.com/guestbook
  newTag: 005043b24561a3da8c97ec777b5724c5e8146bee
