apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- frontend-namespace.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-master-namespace.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml
- redis-slave-namespace.yaml
